FILE_DICT = {
    '.txt': 'Text',
    '.ts': 'Text',
    '.doc': 'Text',
    '.docx': 'Text',
    '.pdf': 'Text',
    '.rtf': 'Text',
    '.csv': 'Data',
    '.xlsx': 'Data',
    '.json': 'Data',
    '.xml': 'Data',
    '.jpg': 'Image',
    '.png': 'Image',
    '.gif': 'Image',
    '.bmp': 'Image',
    '.mp4': 'Video',
    '.avi': 'Video',
    '.mkv': 'Video',
    '.mov': 'Video',
    '.mp3': 'Audio',
    '.wav': 'Audio',
    '.ogg': 'Audio',
    '.flac': 'Audio',
    '.zip': 'Archive',
    '.tar.gz': 'Archive',
    '.tar': 'Archive',
    '.gz': 'Archive',
    '.xz': 'Archive',
    '.exe': 'Executable',
    '.jar': 'Executable',
    '.sh': 'Script',
    '.bash': 'Script',
    '.py': 'Script',
    '.pl': 'Script',
    '.command': 'Script',
    '.app': 'Application'
}


